In [1]:
import os
import pickle

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, balanced_accuracy_score, recall_score
from sklearn.neural_network import MLPClassifier

from xgboost import XGBClassifier

from CSDTools.features import FEATURIZERS, get_or_build_features

In [2]:
CSV_FILE = 'csd_ml.csv'
data = pd.read_csv(CSV_FILE)
data

,smiles_canonical,is_polymorphic,num_inchi_groups,max_distinct_forms,min_distinct_forms
0,B(N1CCc2ccccc21)N1CCc2ccccc21,0,1,1,1
1,B(Nc1ccccc1-c1ccccc1)N(BNc1ccccc1-c1ccccc1)c1c...,0,1,1,1
2,B1C=CC=C(c2ccccn2)N1,0,1,1,1
3,B1N(CP(C2CCCCC2)C2CCCCC2)c2ccccc2N1CP(C1CCCCC1...,0,1,1,1
4,B1N(CP(c2ccccc2)c2ccccc2)c2ccccc2N1CP(c1ccccc1...,0,1,1,1
...,...,...,...,...,...
292368,n1onc2c1NC1Nc3nonc3NC1N2,0,1,1,1
292369,n1onc2c1Nc1nonc1-c1nonc1-2,0,1,1,1
292370,n1snc2c1SC(=C1Sc3nsnc3S1)S2,0,1,1,1
292371,s1c2sc3sc4sc5sc6sc7sc8sc1c1c2c3c4c5c6c7c81,1,1,2,2
292372,s1p2sp3p1p3s2,1,1,2,2

In [3]:
smiles_list  = data['smiles_canonical'].to_list()
labels_full  = data['is_polymorphic'].to_list()

In [4]:
from sklearn.ensemble import (
    RandomForestClassifier, ExtraTreesClassifier, HistGradientBoostingClassifier,
    AdaBoostClassifier
)
from sklearn.linear_model import LogisticRegression, SGDClassifier, RidgeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from imblearn.ensemble import (
    BalancedRandomForestClassifier, EasyEnsembleClassifier, BalancedBaggingClassifier
)

RESULTS_CACHE   = "training_results.csv"
MODEL_CACHE_DIR = "model_cache"
os.makedirs(MODEL_CACHE_DIR, exist_ok=True)

MODELS = {
    "XGBClassifier": XGBClassifier,
    "MLPClassifier": MLPClassifier,
    "LGBMClassifier": LGBMClassifier,
    "HistGB": HistGradientBoostingClassifier,
    "RandomForest": RandomForestClassifier,
    "ExtraTrees": ExtraTreesClassifier,
    "BalancedRF": BalancedRandomForestClassifier,
    "LogisticRegression": LogisticRegression,
    "CatBoost": CatBoostClassifier,
    "AdaBoost": AdaBoostClassifier,
    "EasyEnsemble": EasyEnsembleClassifier,
    "SGD": SGDClassifier,
    "Ridge": RidgeClassifier,
    "GaussianNB": GaussianNB,
    "KNN": KNeighborsClassifier,
    "BalancedBagging": BalancedBaggingClassifier,
}

# Modèles qui acceptent scale_pos_weight à la construction (comme XGB)
SCALE_POS_WEIGHT_MODELS = {"XGBClassifier", "LGBMClassifier"}

# Modèles qui acceptent class_weight='balanced' à la construction
CLASS_WEIGHT_MODELS = {"RandomForest", "ExtraTrees", "HistGB", "LogisticRegression", "SGD", "Ridge"}

# Modèles qui acceptent n_jobs (à combiner avec class_weight quand les deux s'appliquent)
N_JOBS_MODELS = {"RandomForest", "ExtraTrees", "BalancedRF", "SGD", "KNN", "EasyEnsemble", "BalancedBagging"}

# Le reste (MLP, CatBoost, AdaBoost, GaussianNB, KNN seul) gère le déséquilibre autrement ou pas du tout



if os.path.exists(RESULTS_CACHE):
    results = pd.read_csv(RESULTS_CACHE).to_dict("records")
else:
    results = []
done_results = {(r["featurizer"], r["model"]): r for r in results}

for entry in FEATURIZERS:
    cache_key, featurizer, kwargs = entry if isinstance(entry, tuple) else (entry, entry, {})

    pending_models = []
    for model_name in MODELS:
        if (cache_key, model_name) in done_results:
            r = done_results[(cache_key, model_name)]
            print(f"⏭ {cache_key:20s} / {model_name:15s} — "
                  f"acc={r['accuracy']:.3f}  bal_acc={r['balanced_accuracy']:.3f}  recall={r['recall']:.3f}  (cache)")
        else:
            pending_models.append(model_name)

    if not pending_models:
        continue

    try:
        x, valid_ids = get_or_build_features(CSV_FILE, featurizer, smiles_list=smiles_list,
                                              cache_key=cache_key, **kwargs)
    except Exception as e:
        print(f"⛔ {cache_key} featurization failed: {e}")
        continue

    label_list = [labels_full[i] for i in valid_ids]
    x_train, x_test, y_train, y_test = train_test_split(
        x, label_list, test_size=0.2, random_state=42, stratify=label_list
    )

    n_neg = sum(1 for y in y_train if y == 0)
    n_pos = sum(1 for y in y_train if y == 1)
    scale = n_neg / n_pos if n_pos else 1.0
    sample_weight = np.array([scale if y == 1 else 1.0 for y in y_train])

    for model_name in pending_models:
        model_cls = MODELS[model_name]
        try:
            if model_name in SCALE_POS_WEIGHT_MODELS:
                model = model_cls(scale_pos_weight=scale)
                model.fit(x_train, y_train)
            elif model_name in N_JOBS_MODELS and model_name in CLASS_WEIGHT_MODELS:
                if model_name == "RandomForest":
                    model = model_cls(class_weight="balanced_subsample", n_jobs=-1)
                else:
                    model = model_cls(class_weight="balanced", n_jobs=-1)
                model.fit(x_train, y_train)
            elif model_name in N_JOBS_MODELS:  # BalancedRF, pas de class_weight
                model = model_cls(n_jobs=-1)
                model.fit(x_train, y_train)
            elif model_name in CLASS_WEIGHT_MODELS:
                model = model_cls(class_weight="balanced")
                model.fit(x_train, y_train)
            elif model_name == "MLPClassifier":
                model = model_cls(max_iter=300, early_stopping=True)
                model.fit(x_train, y_train, sample_weight=sample_weight)
            elif model_name == "CatBoost":
                model = model_cls(class_weights=[1, scale], verbose=False, iterations=500)
                model.fit(x_train, y_train)
            elif model_name == "AdaBoost":
                model = model_cls(
                    estimator=DecisionTreeClassifier(class_weight="balanced", max_depth=5),
                    n_estimators=100
                )
                model.fit(x_train, y_train)
            else:
                model = model_cls()
                model.fit(x_train, y_train)

            y_pred = model.predict(x_test)
            result = {
                "featurizer":        cache_key,
                "model":             model_name,
                "n_features":        x.shape[1],
                "accuracy":          accuracy_score(y_test, y_pred),
                "balanced_accuracy": balanced_accuracy_score(y_test, y_pred),
                "recall":            recall_score(y_test, y_pred),
            }
            results.append(result)
            done_results[(cache_key, model_name)] = result
            pd.DataFrame(results).to_csv(RESULTS_CACHE, index=False)

            with open(os.path.join(MODEL_CACHE_DIR, f"{cache_key}__{model_name}.pkl"), "wb") as f:
                pickle.dump(model, f)

            print(f"✅ {cache_key:20s} / {model_name:15s} — "
                  f"acc={result['accuracy']:.3f}  bal_acc={result['balanced_accuracy']:.3f}  recall={result['recall']:.3f}")
        except Exception as e:
            print(f"⛔ {cache_key}/{model_name} failed: {e}")

⏭ avalon               / XGBClassifier   — acc=0.860  bal_acc=0.680  recall=0.492  (cache)
⏭ avalon               / MLPClassifier   — acc=0.801  bal_acc=0.684  recall=0.562  (cache)
⏭ avalon               / LGBMClassifier  — acc=0.755  bal_acc=0.684  recall=0.611  (cache)
⏭ avalon               / HistGB          — acc=0.739  bal_acc=0.693  recall=0.644  (cache)
⏭ avalon               / RandomForest    — acc=0.980  bal_acc=0.514  recall=0.029  (cache)
⏭ avalon               / ExtraTrees      — acc=0.978  bal_acc=0.523  recall=0.051  (cache)
⏭ avalon               / BalancedRF      — acc=0.849  bal_acc=0.680  recall=0.504  (cache)
⏭ avalon               / LogisticRegression — acc=0.680  bal_acc=0.680  recall=0.679  (cache)
⏭ avalon               / CatBoost        — acc=0.869  bal_acc=0.674  recall=0.471  (cache)
⏭ avalon               / AdaBoost        — acc=0.697  bal_acc=0.621  recall=0.542  (cache)
⏭ avalon               / EasyEnsemble    — acc=0.673  bal_acc=0.682  recall=0.691  (cache)
⏭ avalon               / SGD             — acc=0.366  bal_acc=0.618  recall=0.880  (cache)
⏭ avalon               / Ridge           — acc=0.677  bal_acc=0.684  recall=0.690  (cache)
⏭ avalon               / GaussianNB      — acc=0.609  bal_acc=0.645  recall=0.683  (cache)
⏭ avalon               / KNN             — acc=0.980  bal_acc=0.511  recall=0.024  (cache)
⏭ avalon               / BalancedBagging — acc=0.839  bal_acc=0.656  recall=0.466  (cache)
⏭ rdkit                / XGBClassifier   — acc=0.886  bal_acc=0.663  recall=0.432  (cache)
⏭ rdkit                / MLPClassifier   — acc=0.929  bal_acc=0.506  recall=0.066  (cache)
⏭ rdkit                / LGBMClassifier  — acc=0.771  bal_acc=0.681  recall=0.587  (cache)
⏭ rdkit                / HistGB          — acc=0.741  bal_acc=0.697  recall=0.651  (cache)
⏭ rdkit                / RandomForest    — acc=0.978  bal_acc=0.520  recall=0.043  (cache)
⏭ rdkit                / ExtraTrees      — acc=0.976  bal_acc=0.531  recall=0.069  (cache)
⏭ rdkit                / BalancedRF      — acc=0.858  bal_acc=0.676  recall=0.487  (cache)
⏭ rdkit                / LogisticRegression — acc=0.703  bal_acc=0.671  recall=0.639  (cache)
⏭ rdkit                / CatBoost        — acc=0.876  bal_acc=0.670  recall=0.456  (cache)
⏭ rdkit                / AdaBoost        — acc=0.661  bal_acc=0.666  recall=0.671  (cache)
⏭ rdkit                / EasyEnsemble    — acc=0.645  bal_acc=0.681  recall=0.718  (cache)
⏭ rdkit                / SGD             — acc=0.593  bal_acc=0.657  recall=0.722  (cache)
⏭ rdkit                / Ridge           — acc=0.688  bal_acc=0.678  recall=0.668  (cache)
⏭ rdkit                / GaussianNB      — acc=0.603  bal_acc=0.661  recall=0.722  (cache)
⏭ rdkit                / KNN             — acc=0.978  bal_acc=0.514  recall=0.031  (cache)
⏭ rdkit                / BalancedBagging — acc=0.840  bal_acc=0.650  recall=0.454  (cache)
⏭ maccs                / XGBClassifier   — acc=0.792  bal_acc=0.688  recall=0.579  (cache)
⏭ maccs                / MLPClassifier   — acc=0.709  bal_acc=0.687  recall=0.664  (cache)
⏭ maccs                / LGBMClassifier  — acc=0.725  bal_acc=0.684  recall=0.642  (cache)
⏭ maccs                / HistGB          — acc=0.734  bal_acc=0.685  recall=0.634  (cache)
⏭ maccs                / RandomForest    — acc=0.969  bal_acc=0.541  recall=0.095  (cache)
⏭ maccs                / ExtraTrees      — acc=0.965  bal_acc=0.548  recall=0.115  (cache)
⏭ maccs                / BalancedRF      — acc=0.825  bal_acc=0.676  recall=0.521  (cache)
⏭ maccs                / LogisticRegression — acc=0.663  bal_acc=0.675  recall=0.688  (cache)
⏭ maccs                / CatBoost        — acc=0.818  bal_acc=0.677  recall=0.530  (cache)
⏭ maccs                / AdaBoost        — acc=0.652  bal_acc=0.657  recall=0.661  (cache)
⏭ maccs                / EasyEnsemble    — acc=0.637  bal_acc=0.668  recall=0.701  (cache)
⏭ maccs                / SGD             — acc=0.343  bal_acc=0.612  recall=0.892  (cache)
⏭ maccs                / Ridge           — acc=0.659  bal_acc=0.676  recall=0.693  (cache)
⏭ maccs                / GaussianNB      — acc=0.657  bal_acc=0.642  recall=0.626  (cache)
⏭ maccs                / KNN             — acc=0.981  bal_acc=0.512  recall=0.026  (cache)
⏭ maccs                / BalancedBagging — acc=0.817  bal_acc=0.660  recall=0.497  (cache)
⏭ atompair-count       / XGBClassifier   — acc=0.795  bal_acc=0.683  recall=0.567  (cache)
⏭ atompair-count       / MLPClassifier   — acc=0.794  bal_acc=0.678  recall=0.557  (cache)
⏭ atompair-count       / LGBMClassifier  — acc=0.754  bal_acc=0.692  recall=0.628  (cache)
⏭ atompair-count       / HistGB          — acc=0.748  bal_acc=0.704  recall=0.658  (cache)
⏭ atompair-count       / RandomForest    — acc=0.981  bal_acc=0.505  recall=0.010  (cache)
⏭ atompair-count       / ExtraTrees      — acc=0.981  bal_acc=0.509  recall=0.019  (cache)
⏭ atompair-count       / BalancedRF      — acc=0.841  bal_acc=0.682  recall=0.517  (cache)
⏭ atompair-count       / LogisticRegression — acc=0.672  bal_acc=0.660  recall=0.648  (cache)
⏭ atompair-count       / CatBoost        — acc=0.850  bal_acc=0.679  recall=0.500  (cache)
⏭ atompair-count       / AdaBoost        — acc=0.687  bal_acc=0.637  recall=0.584  (cache)
⏭ atompair-count       / EasyEnsemble    — acc=0.595  bal_acc=0.668  recall=0.744  (cache)
⏭ atompair-count       / SGD             — acc=0.348  bal_acc=0.586  recall=0.832  (cache)
⏭ atompair-count       / Ridge           — acc=0.675  bal_acc=0.666  recall=0.657  (cache)
⏭ atompair-count       / GaussianNB      — acc=0.211  bal_acc=0.542  recall=0.886  (cache)
⏭ atompair-count       / KNN             — acc=0.980  bal_acc=0.506  recall=0.014  (cache)
⏭ atompair-count       / BalancedBagging — acc=0.832  bal_acc=0.648  recall=0.456  (cache)
⏭ fcfp                 / XGBClassifier   — acc=0.789  bal_acc=0.696  recall=0.599  (cache)
⏭ fcfp                 / MLPClassifier   — acc=0.774  bal_acc=0.702  recall=0.628  (cache)
⏭ fcfp                 / LGBMClassifier  — acc=0.735  bal_acc=0.701  recall=0.666  (cache)
⏭ fcfp                 / HistGB          — acc=0.728  bal_acc=0.691  recall=0.653  (cache)
⏭ fcfp                 / RandomForest    — acc=0.980  bal_acc=0.512  recall=0.027  (cache)
⏭ fcfp                 / ExtraTrees      — acc=0.978  bal_acc=0.521  recall=0.046  (cache)
⏭ fcfp                 / BalancedRF      — acc=0.812  bal_acc=0.695  recall=0.574  (cache)
⏭ fcfp                 / LogisticRegression — acc=0.710  bal_acc=0.684  recall=0.657  (cache)
⏭ fcfp                 / CatBoost        — acc=0.833  bal_acc=0.694  recall=0.550  (cache)
⏭ fcfp                 / AdaBoost        — acc=0.718  bal_acc=0.639  recall=0.557  (cache)
⏭ fcfp                 / EasyEnsemble    — acc=0.632  bal_acc=0.668  recall=0.706  (cache)
⏭ fcfp                 / SGD             — acc=0.725  bal_acc=0.665  recall=0.603  (cache)
⏭ fcfp                 / Ridge           — acc=0.688  bal_acc=0.688  recall=0.688  (cache)
⏭ fcfp                 / GaussianNB      — acc=0.675  bal_acc=0.682  recall=0.689  (cache)
⏭ fcfp                 / KNN             — acc=0.976  bal_acc=0.515  recall=0.037  (cache)
⏭ fcfp                 / BalancedBagging — acc=0.802  bal_acc=0.681  recall=0.555  (cache)
⏭ fcfp-count           / XGBClassifier   — acc=0.790  bal_acc=0.687  recall=0.580  (cache)
⏭ fcfp-count           / MLPClassifier   — acc=0.853  bal_acc=0.677  recall=0.493  (cache)
⏭ fcfp-count           / LGBMClassifier  — acc=0.746  bal_acc=0.691  recall=0.633  (cache)
⏭ fcfp-count           / HistGB          — acc=0.760  bal_acc=0.687  recall=0.612  (cache)
⏭ fcfp-count           / RandomForest    — acc=0.981  bal_acc=0.509  recall=0.019  (cache)
⏭ fcfp-count           / ExtraTrees      — acc=0.980  bal_acc=0.513  recall=0.028  (cache)
⏭ fcfp-count           / BalancedRF      — acc=0.815  bal_acc=0.693  recall=0.566  (cache)
⏭ fcfp-count           / LogisticRegression — acc=0.696  bal_acc=0.647  recall=0.595  (cache)
⏭ fcfp-count           / CatBoost        — acc=0.832  bal_acc=0.670  recall=0.501  (cache)
⏭ fcfp-count           / AdaBoost        — acc=0.718  bal_acc=0.638  recall=0.555  (cache)
⏭ fcfp-count           / EasyEnsemble    — acc=0.633  bal_acc=0.668  recall=0.705  (cache)
⏭ fcfp-count           / SGD             — acc=0.669  bal_acc=0.645  recall=0.621  (cache)
⏭ fcfp-count           / Ridge           — acc=0.674  bal_acc=0.655  recall=0.634  (cache)
⏭ fcfp-count           / GaussianNB      — acc=0.654  bal_acc=0.610  recall=0.565  (cache)
⏭ fcfp-count           / KNN             — acc=0.980  bal_acc=0.507  recall=0.016  (cache)
⏭ fcfp-count           / BalancedBagging — acc=0.807  bal_acc=0.679  recall=0.545  (cache)
⏭ ecfp                 / XGBClassifier   — acc=0.789  bal_acc=0.696  recall=0.599  (cache)
⏭ ecfp                 / MLPClassifier   — acc=0.798  bal_acc=0.705  recall=0.608  (cache)
⏭ ecfp                 / LGBMClassifier  — acc=0.735  bal_acc=0.701  recall=0.666  (cache)
⏭ ecfp                 / HistGB          — acc=0.747  bal_acc=0.697  recall=0.644  (cache)
⏭ ecfp                 / RandomForest    — acc=0.980  bal_acc=0.511  recall=0.024  (cache)
⏭ ecfp                 / ExtraTrees      — acc=0.979  bal_acc=0.523  recall=0.049  (cache)
⏭ ecfp                 / BalancedRF      — acc=0.808  bal_acc=0.696  recall=0.580  (cache)
⏭ ecfp                 / LogisticRegression — acc=0.710  bal_acc=0.684  recall=0.657  (cache)
⏭ ecfp                 / CatBoost        — acc=0.833  bal_acc=0.694  recall=0.550  (cache)
⏭ ecfp                 / AdaBoost        — acc=0.718  bal_acc=0.639  recall=0.557  (cache)
⏭ ecfp                 / EasyEnsemble    — acc=0.631  bal_acc=0.670  recall=0.710  (cache)
⏭ ecfp                 / SGD             — acc=0.699  bal_acc=0.680  recall=0.660  (cache)
⏭ ecfp                 / Ridge           — acc=0.688  bal_acc=0.688  recall=0.688  (cache)
⏭ ecfp                 / GaussianNB      — acc=0.675  bal_acc=0.682  recall=0.689  (cache)
⏭ ecfp                 / KNN             — acc=0.976  bal_acc=0.515  recall=0.037  (cache)
⏭ ecfp                 / BalancedBagging — acc=0.799  bal_acc=0.668  recall=0.532  (cache)
⏭ ecfp-count           / XGBClassifier   — acc=0.790  bal_acc=0.687  recall=0.580  (cache)
⏭ ecfp-count           / MLPClassifier   — acc=0.779  bal_acc=0.684  recall=0.585  (cache)
⏭ ecfp-count           / LGBMClassifier  — acc=0.746  bal_acc=0.691  recall=0.633  (cache)
⏭ ecfp-count           / HistGB          — acc=0.734  bal_acc=0.692  recall=0.649  (cache)
⏭ ecfp-count           / RandomForest    — acc=0.981  bal_acc=0.511  recall=0.023  (cache)
⏭ ecfp-count           / ExtraTrees      — acc=0.980  bal_acc=0.515  recall=0.032  (cache)
⏭ ecfp-count           / BalancedRF      — acc=0.815  bal_acc=0.697  recall=0.576  (cache)
⏭ ecfp-count           / LogisticRegression — acc=0.696  bal_acc=0.647  recall=0.595  (cache)
⏭ ecfp-count           / CatBoost        — acc=0.832  bal_acc=0.670  recall=0.501  (cache)
⏭ ecfp-count           / AdaBoost        — acc=0.718  bal_acc=0.638  recall=0.555  (cache)
⏭ ecfp-count           / EasyEnsemble    — acc=0.629  bal_acc=0.668  recall=0.709  (cache)
⏭ ecfp-count           / SGD             — acc=0.741  bal_acc=0.640  recall=0.534  (cache)
⏭ ecfp-count           / Ridge           — acc=0.674  bal_acc=0.655  recall=0.634  (cache)
⏭ ecfp-count           / GaussianNB      — acc=0.654  bal_acc=0.610  recall=0.565  (cache)
⏭ ecfp-count           / KNN             — acc=0.980  bal_acc=0.507  recall=0.016  (cache)
⏭ ecfp-count           / BalancedBagging — acc=0.804  bal_acc=0.672  recall=0.533  (cache)
⏭ topological          / XGBClassifier   — acc=0.757  bal_acc=0.686  recall=0.613  (cache)
⏭ topological          / MLPClassifier   — acc=0.742  bal_acc=0.698  recall=0.652  (cache)
⏭ topological          / LGBMClassifier  — acc=0.723  bal_acc=0.681  recall=0.637  (cache)
⏭ topological          / HistGB          — acc=0.717  bal_acc=0.693  recall=0.668  (cache)
⏭ topological          / RandomForest    — acc=0.980  bal_acc=0.515  recall=0.033  (cache)
⏭ topological          / ExtraTrees      — acc=0.978  bal_acc=0.519  recall=0.043  (cache)
⏭ topological          / BalancedRF      — acc=0.817  bal_acc=0.690  recall=0.557  (cache)
⏭ topological          / LogisticRegression — acc=0.687  bal_acc=0.677  recall=0.667  (cache)
⏭ topological          / CatBoost        — acc=0.808  bal_acc=0.684  recall=0.555  (cache)
⏭ topological          / EasyEnsemble    — acc=0.522  bal_acc=0.649  recall=0.780  (cache)
⏭ topological          / SGD             — acc=0.700  bal_acc=0.672  recall=0.643  (cache)
⏭ topological          / Ridge           — acc=0.671  bal_acc=0.685  recall=0.699  (cache)
⏭ topological          / GaussianNB      — acc=0.095  bal_acc=0.513  recall=0.949  (cache)
⏭ topological          / KNN             — acc=0.978  bal_acc=0.511  recall=0.027  (cache)
⏭ topological          / BalancedBagging — acc=0.809  bal_acc=0.652  recall=0.489  (cache)
Cache chargé [topological / csd_ml.csv] : (292373, 2048)

KeyboardInterrupt:

In [5]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

results_df = pd.DataFrame(results).sort_values("balanced_accuracy", ascending=False).reset_index(drop=True)
results_df

,featurizer,model,n_features,accuracy,balanced_accuracy,recall
0,desc2D,HistGB,223,0.754536,0.709938,0.663611
1,ecfp,MLPClassifier,2048,0.798136,0.704728,0.607699
2,atompair-count,HistGB,2048,0.748354,0.704091,0.658112
3,topological-count,BalancedRF,2048,0.786182,0.703583,0.617782
4,fcfp,MLPClassifier,2048,0.774177,0.702412,0.627864
5,secfp,GaussianNB,2048,0.703326,0.701380,0.699358
6,fcfp,LGBMClassifier,2048,0.734912,0.701288,0.666361
7,ecfp,LGBMClassifier,2048,0.734912,0.701288,0.666361
8,topological,MLPClassifier,2048,0.742232,0.697824,0.651696
9,ecfp-count,BalancedRF,2048,0.814793,0.697479,0.575619
10,rdkit,HistGB,2048,0.741189,0.696843,0.650779
11,ecfp,HistGB,2048,0.747020,0.696667,0.644363
12,ecfp,BalancedRF,2048,0.807781,0.696155,0.580202
13,ecfp,XGBClassifier,2048,0.788782,0.695916,0.599450
14,fcfp,XGBClassifier,2048,0.788782,0.695916,0.599450
15,secfp,HistGB,2048,0.744951,0.695613,0.644363
16,fcfp,BalancedRF,2048,0.811560,0.694933,0.573786
17,secfp,Ridge,2048,0.691065,0.694683,0.698442
18,ecfp,CatBoost,2048,0.833142,0.694240,0.549954
19,fcfp,CatBoost,2048,0.833142,0.694240,0.549954
20,secfp,MLPClassifier,2048,0.841573,0.694040,0.540788
21,desc2D,LGBMClassifier,223,0.771741,0.693527,0.612282
22,topological,HistGB,2048,0.717007,0.693065,0.668194
23,topological-count,MLPClassifier,2048,0.736999,0.692910,0.647113
24,avalon,HistGB,512,0.739376,0.692773,0.644363
25,fcfp-count,BalancedRF,2048,0.815118,0.692699,0.565536
26,estate,HistGB,79,0.718683,0.692570,0.665445
27,ecfp-count,HistGB,2048,0.733784,0.692171,0.648946
28,atompair-count,LGBMClassifier,2048,0.753724,0.691991,0.627864
29,topological-count,HistGB,2048,0.698965,0.691965,0.684693
30,topological-count,CatBoost,2048,0.801248,0.691927,0.578368
31,topological-count,LGBMClassifier,2048,0.706319,0.691216,0.675527
32,fcfp,HistGB,2048,0.727798,0.690920,0.652612
33,fcfp-count,LGBMClassifier,2048,0.745686,0.690593,0.633364
34,ecfp-count,LGBMClassifier,2048,0.745686,0.690593,0.633364
35,secfp,CatBoost,2048,0.835725,0.690161,0.538955
36,topological,BalancedRF,2048,0.817460,0.689847,0.557287
37,topological-count,XGBClassifier,2048,0.735802,0.689153,0.640697
38,ecfp,Ridge,2048,0.688380,0.688370,0.688359
39,fcfp,Ridge,2048,0.688380,0.688370,0.688359
40,maccs,XGBClassifier,167,0.791860,0.687593,0.579285
41,fcfp-count,HistGB,2048,0.759778,0.687432,0.612282
42,ecfp-count,XGBClassifier,2048,0.790150,0.687171,0.580202
43,fcfp-count,XGBClassifier,2048,0.790150,0.687171,0.580202
44,secfp,SGD,2048,0.692587,0.686916,0.681027
45,maccs,MLPClassifier,167,0.708816,0.686643,0.663611
46,topological,XGBClassifier,2048,0.756819,0.686374,0.613199
47,secfp,LGBMClassifier,2048,0.736092,0.685705,0.633364
48,secfp,LogisticRegression,2048,0.713792,0.685582,0.656279
49,secfp,XGBClassifier,2048,0.799213,0.685495,0.567369
50,maccs,HistGB,167,0.734365,0.685274,0.634280
51,topological,Ridge,2048,0.670526,0.684668,0.699358
52,scaffoldkeys,LGBMClassifier,42,0.731236,0.684579,0.636114
53,avalon,LGBMClassifier,512,0.754784,0.684438,0.611366
54,ecfp,LogisticRegression,2048,0.710235,0.684219,0.657195
55,fcfp,LogisticRegression,2048,0.710235,0.684219,0.657195
56,maccs,LGBMClassifier,167,0.724737,0.683965,0.641613
57,topological,CatBoost,2048,0.808345,0.683854,0.554537
58,avalon,MLPClassifier,512,0.801163,0.683791,0.561870
59,ecfp-count,MLPClassifier,2048,0.778982,0.683730,0.584785
60,avalon,Ridge,512,0.677383,0.683666,0.690192
61,secfp,BalancedRF,2048,0.850056,0.683526,0.510541
62,estate,BalancedRF,79,0.815442,0.683424,0.546288
63,atompair-count,XGBClassifier,2048,0.795143,0.683422,0.567369
64,desc2D,BalancedRF,223,0.839533,0.683110,0.520623
65,atompair-count,BalancedRF,2048,0.841129,0.682124,0.516957
66,scaffoldkeys,HistGB,42,0.736109,0.682117,0.626031
67,avalon,EasyEnsemble,512,0.672988,0.681877,0.691109
68,fcfp,GaussianNB,2048,0.674750,0.681875,0.689276
69,ecfp,GaussianNB,2048,0.674750,0.681875,0.689276
70,estate,MLPClassifier,79,0.747738,0.681298,0.612282
71,rdkit,EasyEnsemble,2048,0.645490,0.680904,0.717690
72,fcfp,BalancedBagging,2048,0.802155,0.680700,0.554537
73,topological,LGBMClassifier,2048,0.722702,0.680681,0.637030
74,rdkit,LGBMClassifier,2048,0.771218,0.680673,0.586618
75,ecfp,SGD,2048,0.699290,0.679992,0.659945
76,avalon,LogisticRegression,512,0.680257,0.679735,0.679193
77,avalon,BalancedRF,512,0.848722,0.679699,0.504125
78,avalon,XGBClassifier,512,0.860162,0.679684,0.492209
79,estate,XGBClassifier,79,0.751398,0.679566,0.604950
80,estate,CatBoost,79,0.795366,0.679039,0.558203
81,fcfp-count,BalancedBagging,2048,0.807473,0.678914,0.545371
82,atompair-count,CatBoost,2048,0.850312,0.678711,0.500458
83,rdkit,Ridge,2048,0.688192,0.678383,0.668194
84,atompair-count,MLPClassifier,2048,0.794032,0.677910,0.557287
85,estate,LGBMClassifier,79,0.720735,0.677431,0.632447
86,topological,LogisticRegression,2048,0.686960,0.677306,0.667278
87,maccs,CatBoost,167,0.818025,0.676647,0.529789
88,fcfp-count,MLPClassifier,2048,0.853065,0.676517,0.493126
89,maccs,BalancedRF,167,0.825276,0.675846,0.520623
90,rdkit,BalancedRF,2048,0.857631,0.675696,0.486709
91,maccs,Ridge,167,0.658709,0.675500,0.692942
92,maccs,LogisticRegression,167,0.662899,0.675387,0.688359
93,pharm2d-gobbi,HistGB,2048,0.696298,0.674870,0.652612
94,scaffoldkeys,XGBClassifier,42,0.785755,0.674592,0.559120
95,avalon,CatBoost,512,0.869431,0.674066,0.471127
96,scaffoldkeys,MLPClassifier,42,0.636409,0.674029,0.713107
97,scaffoldkeys,CatBoost,42,0.817324,0.673592,0.524290
98,pharm2d-gobbi,Ridge,2048,0.650500,0.673566,0.697525
99,pharm2d-gobbi,MLPClassifier,2048,0.718375,0.672632,0.625115
100,topological,SGD,2048,0.699735,0.672126,0.643446
101,estate,EasyEnsemble,79,0.633228,0.671959,0.712191
102,ecfp-count,BalancedBagging,2048,0.804463,0.671536,0.533456
103,rdkit,LogisticRegression,2048,0.702916,0.671498,0.638863
104,pharm2d-pmapper,HistGB,2048,0.679470,0.670792,0.661778
105,rdkit,CatBoost,2048,0.876032,0.670236,0.456462
106,ecfp,EasyEnsemble,2048,0.631056,0.669953,0.710357
107,fcfp-count,CatBoost,2048,0.832202,0.669933,0.501375
108,ecfp-count,CatBoost,2048,0.832202,0.669933,0.501375
109,scaffoldkeys,BalancedRF,42,0.831039,0.669790,0.502291
110,atompair-count,EasyEnsemble,2048,0.595348,0.668394,0.744271
111,maccs,EasyEnsemble,167,0.636665,0.668315,0.701192
112,ecfp-count,EasyEnsemble,2048,0.629431,0.668226,0.708524
113,fcfp,EasyEnsemble,2048,0.632065,0.668219,0.705775
114,pharm2d-pmapper,MLPClassifier,2048,0.763540,0.668219,0.569203
115,pharm2d-gobbi,LGBMClassifier,2048,0.737905,0.668195,0.595784
116,fcfp-count,EasyEnsemble,2048,0.632510,0.667996,0.704858
117,pharm2d-gobbi,CatBoost,2048,0.816879,0.667971,0.513291
118,ecfp,BalancedBagging,2048,0.798837,0.667770,0.531622
119,desc2D,BalancedBagging,223,0.828417,0.667106,0.499542
120,erg,HistGB,315,0.682274,0.666826,0.650779
121,atompair-count,Ridge,2048,0.675451,0.666497,0.657195
122,pharm2d-gobbi,BalancedRF,2048,0.847798,0.666191,0.477544
123,rdkit,AdaBoost,2048,0.660932,0.665843,0.670944
124,erg,XGBClassifier,315,0.761744,0.665505,0.565536
125,erg,LGBMClassifier,315,0.690534,0.665190,0.638863
126,fcfp,SGD,2048,0.724600,0.665013,0.603116
127,pharm2d-gobbi,XGBClassifier,2048,0.774622,0.664424,0.549954
128,pharm2d-gobbi,LogisticRegression,2048,0.669602,0.664416,0.659028
129,cats,HistGB,189,0.686071,0.663815,0.640697
130,rdkit,XGBClassifier,2048,0.886481,0.663421,0.431714
131,topological-count,Ridge,2048,0.647507,0.663049,0.679193
132,erg,CatBoost,315,0.794904,0.662169,0.524290
133,desc2D,XGBClassifier,223,0.873754,0.661881,0.441797
134,rdkit,GaussianNB,2048,0.602599,0.661299,0.722273
135,topological-count,LogisticRegression,2048,0.657939,0.660721,0.663611
136,pharm2d-pmapper,LGBMClassifier,2048,0.711928,0.660355,0.606783
137,atompair-count,LogisticRegression,2048,0.672048,0.660267,0.648029
138,pharm2d-pmapper,Ridge,2048,0.657016,0.660251,0.663611
139,topological-count,BalancedBagging,2048,0.805147,0.660195,0.509624
140,pharm2d-pmapper,XGBClassifier,2048,0.757144,0.660015,0.559120
141,maccs,BalancedBagging,167,0.816588,0.659730,0.496792
142,cats2d,HistGB,189,0.681094,0.659032,0.636114
143,secfp,BalancedBagging,2048,0.832578,0.658436,0.477544
144,pharm2d-gobbi,SGD,2048,0.624198,0.658366,0.693859
145,pharm2d-pmapper,CatBoost,2048,0.808944,0.657634,0.500458
146,pharm2d-pmapper,BalancedRF,2048,0.855306,0.656978,0.450962
147,maccs,AdaBoost,167,0.652484,0.656593,0.660862
148,rdkit,SGD,2048,0.593262,0.656541,0.722273
149,avalon,BalancedBagging,512,0.839025,0.655876,0.465628
150,cats2d,XGBClassifier,189,0.770928,0.655798,0.536205
151,cats,XGBClassifier,189,0.770928,0.655798,0.536205
152,erg,BalancedRF,315,0.820470,0.655414,0.483960
153,fcfp-count,Ridge,2048,0.674237,0.654638,0.634280
154,ecfp-count,Ridge,2048,0.674237,0.654638,0.634280
155,estate,BalancedBagging,79,0.807285,0.654541,0.495875
156,pharm2d-pmapper,LogisticRegression,2048,0.669380,0.654412,0.638863
157,cats2d,LGBMClassifier,189,0.696588,0.654338,0.610449
158,cats,LGBMClassifier,189,0.696588,0.654338,0.610449
159,scaffoldkeys,EasyEnsemble,42,0.631398,0.653043,0.675527
160,topological,BalancedBagging,2048,0.809406,0.652474,0.489459
161,desc2D,CatBoost,223,0.896961,0.651676,0.396884
162,rdkit,BalancedBagging,2048,0.839538,0.650293,0.453712
163,scaffoldkeys,AdaBoost,42,0.685558,0.650066,0.613199
164,topological,EasyEnsemble,2048,0.522411,0.648766,0.780018
165,estate,LogisticRegression,79,0.592852,0.648689,0.706691
166,pharm2d-gobbi,EasyEnsemble,2048,0.605763,0.648524,0.692942
167,erg,MLPClassifier,315,0.747790,0.648505,0.545371
168,cats2d,CatBoost,189,0.811321,0.648504,0.479377
169,cats,CatBoost,189,0.811321,0.648504,0.479377
170,pharm2d-pmapper,SGD,2048,0.710133,0.648201,0.583868
171,atompair-count,BalancedBagging,2048,0.832441,0.647576,0.455545
172,erg,EasyEnsemble,315,0.628559,0.646651,0.665445
173,ecfp-count,LogisticRegression,2048,0.696246,0.646520,0.594867
174,fcfp-count,LogisticRegression,2048,0.696246,0.646520,0.594867
175,scaffoldkeys,BalancedBagging,42,0.825122,0.646095,0.460128
176,cats2d,BalancedRF,189,0.825755,0.645518,0.458295
177,avalon,GaussianNB,512,0.609029,0.645243,0.682860
178,fcfp-count,SGD,2048,0.668525,0.644985,0.620532
179,estate,Ridge,79,0.585327,0.644855,0.706691
180,secfp,EasyEnsemble,2048,0.581291,0.643698,0.708524
181,pharm2d-pmapper,EasyEnsemble,2048,0.611287,0.643695,0.677360
182,cats,BalancedRF,189,0.823035,0.643683,0.457379
183,pharm2d-gobbi,AdaBoost,2048,0.641060,0.642680,0.644363
184,erg,BalancedBagging,315,0.792236,0.642377,0.486709
185,cats,MLPClassifier,189,0.691937,0.642077,0.590284
186,maccs,GaussianNB,167,0.656999,0.641809,0.626031
187,ecfp-count,SGD,2048,0.741428,0.639868,0.534372
188,cats,EasyEnsemble,189,0.653698,0.639678,0.625115
189,cats2d,EasyEnsemble,189,0.638204,0.639427,0.640697
190,fcfp,AdaBoost,2048,0.718375,0.639362,0.557287
191,ecfp,AdaBoost,2048,0.718375,0.639362,0.557287
192,fcfp-count,AdaBoost,2048,0.718136,0.638341,0.555454
193,ecfp-count,AdaBoost,2048,0.718136,0.638341,0.555454
194,cats2d,LogisticRegression,189,0.638478,0.637768,0.637030
195,cats,LogisticRegression,189,0.638478,0.637768,0.637030
196,cats2d,MLPClassifier,189,0.714853,0.637568,0.557287
197,atompair-count,AdaBoost,2048,0.687388,0.636612,0.583868
198,estate,AdaBoost,79,0.686994,0.636412,0.583868
199,topological-count,EasyEnsemble,2048,0.497033,0.636285,0.780935
200,cats,Ridge,189,0.614827,0.636058,0.658112
201,cats2d,Ridge,189,0.614827,0.636058,0.658112
202,pharm2d-pmapper,BalancedBagging,2048,0.813818,0.635390,0.450046
203,erg,Ridge,315,0.582505,0.634876,0.689276
204,pharm2d-gobbi,BalancedBagging,2048,0.818794,0.634778,0.443630
205,erg,LogisticRegression,315,0.584250,0.633966,0.685610
206,scaffoldkeys,Ridge,42,0.573117,0.631441,0.692026
207,scaffoldkeys,LogisticRegression,42,0.581479,0.630307,0.681027
208,cats2d,BalancedBagging,189,0.798923,0.626452,0.447296
209,cats2d,AdaBoost,189,0.649919,0.625164,0.599450
210,cats,AdaBoost,189,0.649919,0.625164,0.599450
211,estate,SGD,79,0.522531,0.624550,0.730522
212,avalon,AdaBoost,512,0.696896,0.620776,0.541705
213,scaffoldkeys,GaussianNB,42,0.538538,0.619667,0.703941
214,cats,BalancedBagging,189,0.799470,0.619537,0.432631
215,avalon,SGD,512,0.365524,0.617835,0.879927
216,maccs,SGD,167,0.342522,0.611960,0.891842
217,fcfp-count,GaussianNB,2048,0.654382,0.610354,0.564620
218,ecfp-count,GaussianNB,2048,0.654382,0.610354,0.564620
219,pharm2d-pmapper,AdaBoost,2048,0.756528,0.607999,0.453712
220,topological-count,SGD,2048,0.794425,0.603929,0.406049
221,erg,ExtraTrees,315,0.905960,0.595567,0.273144
222,cats,SGD,189,0.402172,0.592898,0.791017
223,erg,RandomForest,315,0.918769,0.586358,0.241063
224,atompair-count,SGD,2048,0.348029,0.585543,0.832264
225,pharm2d-gobbi,GaussianNB,2048,0.376965,0.584551,0.800183
226,topological-count,GaussianNB,2048,0.288636,0.569219,0.860678
227,cats,ExtraTrees,189,0.949141,0.564068,0.164070
228,cats2d,ExtraTrees,189,0.949209,0.563653,0.163153
229,scaffoldkeys,SGD,42,0.931509,0.560030,0.174152
230,cats2d,RandomForest,189,0.953912,0.559755,0.150321
231,cats,RandomForest,189,0.954288,0.559498,0.149404
232,pharm2d-gobbi,ExtraTrees,2048,0.960581,0.558658,0.141155
233,pharm2d-pmapper,GaussianNB,2048,0.230885,0.556429,0.894592
234,pharm2d-pmapper,ExtraTrees,2048,0.955964,0.555856,0.140238
235,pharm2d-gobbi,RandomForest,2048,0.963540,0.553871,0.128323
236,pharm2d-pmapper,RandomForest,2048,0.958974,0.551994,0.129239
237,maccs,ExtraTrees,167,0.965387,0.548068,0.114574
238,erg,SGD,315,0.572176,0.543743,0.514207
239,atompair-count,GaussianNB,2048,0.210500,0.541997,0.886343
240,maccs,RandomForest,167,0.969252,0.540596,0.095325
241,scaffoldkeys,ExtraTrees,42,0.973578,0.537406,0.084326
242,cats2d,GaussianNB,189,0.897478,0.534598,0.157654
243,cats,GaussianNB,189,0.897478,0.534598,0.157654
244,estate,ExtraTrees,79,0.971458,0.532729,0.076994
245,estate,RandomForest,79,0.972809,0.531619,0.073327
246,rdkit,ExtraTrees,2048,0.975887,0.530939,0.068744
247,scaffoldkeys,RandomForest,42,0.976007,0.530101,0.066911
248,erg,AdaBoost,315,0.807405,0.527819,0.237397
249,cats2d,SGD,189,0.848243,0.527047,0.193401
250,avalon,ExtraTrees,512,0.977512,0.523225,0.051329
251,ecfp,ExtraTrees,2048,0.978829,0.522997,0.049496
252,topological-count,ExtraTrees,2048,0.978504,0.521033,0.045830
253,fcfp,ExtraTrees,2048,0.978452,0.521007,0.045830
254,rdkit,RandomForest,2048,0.978264,0.519562,0.043080
255,topological,ExtraTrees,2048,0.977991,0.519423,0.043080
256,topological-count,RandomForest,2048,0.979735,0.515815,0.033914
257,desc2D,ExtraTrees,223,0.979597,0.515746,0.033914
258,topological,RandomForest,2048,0.979855,0.515427,0.032997
259,secfp,ExtraTrees,2048,0.979786,0.515392,0.032997
260,fcfp,KNN,2048,0.975956,0.515239,0.036664
261,ecfp,KNN,2048,0.975956,0.515239,0.036664
262,ecfp-count,ExtraTrees,2048,0.980248,0.515178,0.032081
263,secfp,KNN,2048,0.964429,0.514761,0.047663
264,rdkit,KNN,2048,0.978316,0.513744,0.031164
265,avalon,RandomForest,512,0.979649,0.513524,0.029331
266,topological,GaussianNB,2048,0.094502,0.513467,0.948671
267,fcfp-count,ExtraTrees,2048,0.980299,0.513406,0.028414
268,fcfp,RandomForest,2048,0.980180,0.512445,0.026581
269,maccs,KNN,167,0.980641,0.512231,0.025665
270,topological,KNN,2048,0.978145,0.511409,0.026581
271,ecfp-count,RandomForest,2048,0.980881,0.511004,0.022915
272,ecfp,RandomForest,2048,0.979957,0.510983,0.023831
273,erg,GaussianNB,315,0.091150,0.510860,0.946838
274,avalon,KNN,512,0.979530,0.510766,0.023831
275,atompair-count,ExtraTrees,2048,0.980932,0.509232,0.019248
276,fcfp-count,RandomForest,2048,0.980812,0.509171,0.019248
277,estate,GaussianNB,79,0.052125,0.507611,0.980752
278,secfp,RandomForest,2048,0.980590,0.507260,0.015582
279,erg,KNN,315,0.980710,0.506871,0.014665
280,fcfp-count,KNN,2048,0.979649,0.506780,0.015582
281,ecfp-count,KNN,2048,0.979649,0.506780,0.015582
282,pharm2d-gobbi,KNN,2048,0.980573,0.506352,0.013749
283,atompair-count,KNN,2048,0.980214,0.506169,0.013749
284,rdkit,MLPClassifier,2048,0.929252,0.505829,0.065995
285,atompair-count,RandomForest,2048,0.981291,0.504919,0.010082
286,pharm2d-pmapper,KNN,2048,0.980316,0.504872,0.010999
287,topological-count,KNN,2048,0.979393,0.504851,0.011916
288,estate,KNN,79,0.980607,0.504121,0.009166
289,cats2d,KNN,189,0.980436,0.504034,0.009166
290,cats,KNN,189,0.980436,0.504034,0.009166
291,desc2D,RandomForest,223,0.981137,0.503942,0.008249
292,scaffoldkeys,KNN,42,0.980744,0.501943,0.004583

In [6]:
best_featurizer, best_model_name = results_df.loc[0, ["featurizer", "model"]]
with open(os.path.join(MODEL_CACHE_DIR, f"{best_featurizer}__{best_model_name}.pkl"), "rb") as f:
    best_model = pickle.load(f)

with open("best_polymorph_model.pkl", "wb") as f:
    pickle.dump(best_model, f)

print(f"Meilleur modèle sauvegardé : {best_model_name} / {best_featurizer}")

Meilleur modèle sauvegardé : HistGB / desc2D

In [4]:
import time
import json as jsonlib

from sklearn.model_selection import RandomizedSearchCV, StratifiedKFold
from scipy.stats import randint, uniform, loguniform

from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.linear_model import LogisticRegression, SGDClassifier, RidgeClassifier
from sklearn.naive_bayes import GaussianNB
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from imblearn.ensemble import BalancedRandomForestClassifier

RESULTS_CACHE   = "training_results.csv"

TOP_N = 50
TUNING_RESULTS_CACHE  = "tuning_results.csv"
TUNED_MODEL_CACHE_DIR = "tuned_model_cache"
os.makedirs(TUNED_MODEL_CACHE_DIR, exist_ok=True)

base_results = pd.read_csv(RESULTS_CACHE)
before_lookup = {(r["featurizer"], r["model"]): r for r in base_results.to_dict("records")}

top_combos = (
    base_results
    .sort_values("balanced_accuracy", ascending=False)
    .head(TOP_N)[["featurizer", "model"]]
    .itertuples(index=False, name=None)
)
top_combos = list(top_combos)

# Rapides d'abord, lents en dernier (ordre observé empiriquement sur les runs déjà faits)
MODEL_SPEED_ORDER = [
    "Ridge", "GaussianNB", "SGD", "LGBMClassifier", "LogisticRegression",
    "BalancedRF", "XGBClassifier", "CatBoost", "HistGB", "MLPClassifier",
]
top_combos = sorted(top_combos, key=lambda c: MODEL_SPEED_ORDER.index(c[1]))

FEATURIZER_LOOKUP = {}
for entry in FEATURIZERS:
    cache_key, featurizer, kwargs = entry if isinstance(entry, tuple) else (entry, entry, {})
    FEATURIZER_LOOKUP[cache_key] = (featurizer, kwargs)

PARAM_DISTRIBUTIONS = {
    "HistGB": dict(
        max_iter=randint(100, 1000),
        max_depth=randint(3, 15),
        max_leaf_nodes=randint(15, 127),
        learning_rate=loguniform(0.01, 0.3),
        l2_regularization=loguniform(1e-3, 10),
        min_samples_leaf=randint(5, 100),
    ),
    "LGBMClassifier": dict(
        n_estimators=randint(100, 600),
        num_leaves=randint(15, 200),
        max_depth=randint(3, 15),
        learning_rate=loguniform(0.01, 0.3),
        min_child_samples=randint(5, 200),
        reg_alpha=loguniform(1e-3, 10),
        reg_lambda=loguniform(1e-3, 10),
        subsample=uniform(0.6, 0.4),
        colsample_bytree=uniform(0.6, 0.4),
    ),
    "XGBClassifier": dict(
        n_estimators=randint(100, 1000),
        max_depth=randint(3, 12),
        learning_rate=loguniform(0.01, 0.3),
        min_child_weight=randint(1, 20),
        subsample=uniform(0.6, 0.4),
        colsample_bytree=uniform(0.6, 0.4),
        reg_alpha=loguniform(1e-3, 30),
        reg_lambda=loguniform(1e-3, 10),
        gamma=uniform(0, 10),
    ),
    "CatBoost": dict(
        iterations=randint(200, 800),
        depth=randint(4, 10),
        learning_rate=loguniform(0.01, 0.3),
        l2_leaf_reg=loguniform(1, 20),
    ),
    "BalancedRF": dict(
        n_estimators=randint(100, 500),
        max_depth=randint(5, 30),
        min_samples_leaf=randint(1, 50),
        max_features=uniform(0.1, 0.9),
    ),
    "MLPClassifier": dict(
        hidden_layer_sizes=[(64,), (128,), (256,), (128, 64), (256, 128), (128, 64, 32)],
        alpha=loguniform(1e-5, 1e-1),
        learning_rate_init=loguniform(1e-4, 1e-2),
        activation=["relu", "tanh"],
    ),
    "Ridge": dict(
        alpha=loguniform(1e-3, 300),
    ),
    "GaussianNB": dict(
        var_smoothing=loguniform(1e-11, 1e-6),
    ),
    "LogisticRegression": dict(
        C=loguniform(1e-4, 100),
    ),
    "SGD": dict(
        alpha=loguniform(1e-6, 1e-1),
        loss=["hinge", "log_loss", "modified_huber"],
        penalty=["l2", "l1", "elasticnet"],
    ),
}

# Modèles lents / ensembles coûteux -> moins de candidats pour rester raisonnable
N_ITER_BY_MODEL = {
    "MLPClassifier": 10,
    "CatBoost": 12,
    "BalancedRF": 12,
    "Ridge": 8,
    "GaussianNB": 8,
    "SGD": 8,
}
DEFAULT_N_ITER = 20
CV_FOLDS = 3


def build_base_estimator(model_name, scale):
    if model_name == "XGBClassifier":
        return XGBClassifier(scale_pos_weight=scale)
    if model_name == "LGBMClassifier":
        return LGBMClassifier(scale_pos_weight=scale, verbosity=-1)
    if model_name == "CatBoost":
        # scale_pos_weight (float) plutôt que class_weights (liste) : cette dernière
        # cassait le clone() de sklearn utilisé par RandomizedSearchCV
        return CatBoostClassifier(scale_pos_weight=scale, verbose=False)
    if model_name == "HistGB":
        return HistGradientBoostingClassifier(class_weight="balanced")
    if model_name == "BalancedRF":
        return BalancedRandomForestClassifier(n_jobs=-1)
    if model_name == "Ridge":
        return RidgeClassifier(class_weight="balanced")
    if model_name == "GaussianNB":
        return GaussianNB()
    if model_name == "MLPClassifier":
        return MLPClassifier(max_iter=300, early_stopping=True)
    if model_name == "LogisticRegression":
        return LogisticRegression(class_weight="balanced")
    if model_name == "SGD":
        # max_iter plafonné + early_stopping : évite la convergence très lente
        # observée avec certains tirages (alpha faible / elasticnet) sur ce dataset
        return SGDClassifier(class_weight="balanced", n_jobs=-1, max_iter=200, early_stopping=True)
    raise ValueError(f"Pas de config de tuning pour {model_name}")


def tune_combo(model_name, x_train, y_train, sample_weight, scale, n_iter, cv):
    base = build_base_estimator(model_name, scale)
    search = RandomizedSearchCV(
        base, PARAM_DISTRIBUTIONS[model_name],
        n_iter=n_iter,
        cv=StratifiedKFold(cv, shuffle=True, random_state=42),
        scoring="balanced_accuracy",
        random_state=42,
        n_jobs=1,
        refit=True,
    )
    fit_kwargs = {}
    if model_name == "MLPClassifier":
        fit_kwargs["sample_weight"] = sample_weight
    search.fit(x_train, y_train, **fit_kwargs)
    return search

In [8]:
# Test rapide sur 1 combo (n_iter/cv réduits) pour valider que le pipeline tourne avant le run complet
_test_key, _test_model = "secfp", "Ridge"
_featurizer, _kwargs = FEATURIZER_LOOKUP[_test_key]

_x, _valid_ids = get_or_build_features(CSV_FILE, _featurizer, smiles_list=smiles_list,
                                        cache_key=_test_key, **_kwargs)
_label_list = [labels_full[i] for i in _valid_ids]
_x_train, _x_test, _y_train, _y_test = train_test_split(
    _x, _label_list, test_size=0.2, random_state=42, stratify=_label_list
)
_n_neg = sum(1 for y in _y_train if y == 0)
_n_pos = sum(1 for y in _y_train if y == 1)
_scale = _n_neg / _n_pos if _n_pos else 1.0
_sample_weight = np.array([_scale if y == 1 else 1.0 for y in _y_train])

_t0 = time.time()
_search = tune_combo(_test_model, _x_train, _y_train, _sample_weight, _scale, n_iter=3, cv=2)
_elapsed = time.time() - _t0

_y_pred = _search.best_estimator_.predict(_x_test)
print(f"OK — {_test_key}/{_test_model} tuning (3 iters, cv=2) en {_elapsed:.1f}s")
_bal_acc_before = before_lookup[(_test_key, _test_model)]["balanced_accuracy"]
print(f"balanced_accuracy avant tuning : {_bal_acc_before:.3f}")
print(f"balanced_accuracy après ce mini-test : {balanced_accuracy_score(_y_test, _y_pred):.3f}")
print(f"best_params (mini-test) : {_search.best_params_}")

Cache chargé [secfp / csd_ml.csv] : (292373, 2048)
OK — secfp/Ridge tuning (3 iters, cv=2) en 39.4s
balanced_accuracy avant tuning : 0.695
balanced_accuracy après ce mini-test : 0.695
best_params (mini-test) : {'alpha': np.float64(56.69849511478853)}

In [ ]:
if os.path.exists(TUNING_RESULTS_CACHE):
    tuning_results = pd.read_csv(TUNING_RESULTS_CACHE).to_dict("records")
else:
    tuning_results = []
tuning_done = {(r["featurizer"], r["model"]): r for r in tuning_results}

for cache_key, model_name in top_combos:
    if (cache_key, model_name) in tuning_done:
        r = tuning_done[(cache_key, model_name)]
        print(f"⏭ {cache_key:20s} / {model_name:15s} — "
              f"bal_acc={r['balanced_accuracy']:.3f} (avant tuning: {r['balanced_accuracy_before']:.3f})  (cache)")
        continue

    featurizer, kwargs = FEATURIZER_LOOKUP[cache_key]
    try:
        x, valid_ids = get_or_build_features(CSV_FILE, featurizer, smiles_list=smiles_list,
                                              cache_key=cache_key, **kwargs)
    except Exception as e:
        print(f"⛔ {cache_key} featurization failed: {e}")
        continue

    label_list = [labels_full[i] for i in valid_ids]
    x_train, x_test, y_train, y_test = train_test_split(
        x, label_list, test_size=0.2, random_state=42, stratify=label_list
    )

    n_neg = sum(1 for y in y_train if y == 0)
    n_pos = sum(1 for y in y_train if y == 1)
    scale = n_neg / n_pos if n_pos else 1.0
    sample_weight = np.array([scale if y == 1 else 1.0 for y in y_train])

    n_iter = N_ITER_BY_MODEL.get(model_name, DEFAULT_N_ITER)

    try:
        t0 = time.time()
        search = tune_combo(model_name, x_train, y_train, sample_weight, scale, n_iter, CV_FOLDS)
        elapsed = time.time() - t0

        best_model = search.best_estimator_
        y_pred = best_model.predict(x_test)
        bal_acc_before = before_lookup.get((cache_key, model_name), {}).get("balanced_accuracy")

        result = {
            "featurizer":               cache_key,
            "model":                    model_name,
            "balanced_accuracy_before": bal_acc_before,
            "accuracy":                 accuracy_score(y_test, y_pred),
            "balanced_accuracy":        balanced_accuracy_score(y_test, y_pred),
            "recall":                   recall_score(y_test, y_pred),
            "cv_best_score":            search.best_score_,
            "best_params":              jsonlib.dumps(search.best_params_),
            "n_iter":                   n_iter,
            "elapsed_sec":              round(elapsed, 1),
        }
        tuning_results.append(result)
        tuning_done[(cache_key, model_name)] = result
        pd.DataFrame(tuning_results).to_csv(TUNING_RESULTS_CACHE, index=False)

        with open(os.path.join(TUNED_MODEL_CACHE_DIR, f"{cache_key}__{model_name}.pkl"), "wb") as f:
            pickle.dump(best_model, f)

        delta = result["balanced_accuracy"] - bal_acc_before if bal_acc_before is not None else float("nan")
        print(f"✅ {cache_key:20s} / {model_name:15s} — "
              f"bal_acc={result['balanced_accuracy']:.3f} (avant: {bal_acc_before:.3f}, Δ={delta:+.3f})  "
              f"[{elapsed:.0f}s, {n_iter} iters]")
    except Exception as e:
        print(f"⛔ {cache_key}/{model_name} failed: {e}")

Cache chargé [secfp / csd_ml.csv] : (292373, 2048)
✅ secfp                / Ridge           — bal_acc=0.696 (avant: 0.695, Δ=+0.001)  [167s, 8 iters]
Cache chargé [ecfp / csd_ml.csv] : (292373, 2048)
✅ ecfp                 / Ridge           — bal_acc=0.696 (avant: 0.688, Δ=+0.007)  [167s, 8 iters]
Cache chargé [fcfp / csd_ml.csv] : (292373, 2048)
✅ fcfp                 / Ridge           — bal_acc=0.696 (avant: 0.688, Δ=+0.007)  [177s, 8 iters]
⏭ secfp                / GaussianNB      — bal_acc=0.701 (avant tuning: 0.701)  (cache)
⏭ secfp                / SGD             — bal_acc=0.707 (avant tuning: 0.687)  (cache)
Cache chargé [fcfp / csd_ml.csv] : (292373, 2048)

/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

✅ fcfp                 / LGBMClassifier  — bal_acc=0.698 (avant: 0.701, Δ=-0.003)  [229s, 20 iters]
Cache chargé [ecfp / csd_ml.csv] : (292373, 2048)

/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

✅ ecfp                 / LGBMClassifier  — bal_acc=0.698 (avant: 0.701, Δ=-0.003)  [236s, 20 iters]
Cache chargé [desc2D / csd_ml.csv] : (292362, 223)

/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

✅ desc2D               / LGBMClassifier  — bal_acc=0.706 (avant: 0.694, Δ=+0.012)  [282s, 20 iters]
Cache chargé [atompair-count / csd_ml.csv] : (292373, 2048)

/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

✅ atompair-count       / LGBMClassifier  — bal_acc=0.698 (avant: 0.692, Δ=+0.006)  [445s, 20 iters]
Cache chargé [topological-count / csd_ml.csv] : (292373, 2048)

/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

✅ topological-count    / LGBMClassifier  — bal_acc=0.703 (avant: 0.691, Δ=+0.012)  [233s, 20 iters]
Cache chargé [fcfp-count / csd_ml.csv] : (292373, 2048)

/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

✅ fcfp-count           / LGBMClassifier  — bal_acc=0.706 (avant: 0.691, Δ=+0.016)  [258s, 20 iters]
Cache chargé [ecfp-count / csd_ml.csv] : (292373, 2048)

/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

✅ ecfp-count           / LGBMClassifier  — bal_acc=0.706 (avant: 0.691, Δ=+0.016)  [239s, 20 iters]
Cache chargé [secfp / csd_ml.csv] : (292373, 2048)

/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/arthur/miniforge3/envs/polymorph/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

✅ secfp                / LGBMClassifier  — bal_acc=0.698 (avant: 0.686, Δ=+0.012)  [253s, 20 iters]
⏭ secfp                / LogisticRegression — bal_acc=0.706 (avant tuning: 0.686)  (cache)
⏭ topological-count    / BalancedRF      — bal_acc=0.683 (avant tuning: 0.704)  (cache)
⏭ ecfp-count           / BalancedRF      — bal_acc=0.691 (avant tuning: 0.697)  (cache)
⏭ ecfp                 / BalancedRF      — bal_acc=0.689 (avant tuning: 0.696)  (cache)
⏭ fcfp                 / BalancedRF      — bal_acc=0.694 (avant tuning: 0.695)  (cache)
⏭ fcfp-count           / BalancedRF      — bal_acc=0.690 (avant tuning: 0.693)  (cache)
⏭ topological          / BalancedRF      — bal_acc=0.686 (avant tuning: 0.690)  (cache)
Cache chargé [ecfp / csd_ml.csv] : (292373, 2048)

In [ ]:
TUNING_RESULTS_CACHE  = "tuning_results.csv"
if os.path.exists(TUNING_RESULTS_CACHE):
    tuning_results = pd.read_csv(TUNING_RESULTS_CACHE).to_dict("records")
else:
    tuning_results = []

pd.set_option("display.max_rows", None)
tuning_df = pd.DataFrame(tuning_results).sort_values("balanced_accuracy", ascending=False).reset_index(drop=True)
tuning_df